export const generationOptions = [
  { label: "Generation 1", value: "generation-i" },
  { label: "Generation 2", value: "generation-ii" },
  { label: "Generation 3", value: "generation-iii" },
  { label: "Generation 4", value: "generation-iv" },
  { label: "Generation 5", value: "generation-v" },
  { label: "Generation 6", value: "generation-vi" },
  { label: "Generation 7", value: "generation-vii" },
  { label: "Generation 8", value: "generation-viii" },
  { label: "Generation 9", value: "generation-ix" },
];

export const typeOptions = [
  { label: "Steel", value: "steel" },
  { label: "Water", value: "water" },
  { label: "Dragon", value: "dragon" },
  { label: "Eletric", value: "electric" },
  { label: "Ghost", value: "ghost" },
  { label: "Fairy", value: "fairy" },
  { label: "Fire", value: "fire" },
  { label: "Ice", value: "ice" },
  { label: "Bug", value: "bug" },
  { label: "Fighting", value: "fighting" },
  { label: "Normal", value: "normal" },
  { label: "Rock", value: "rock" },
  { label: "Grass", value: "grass" },
  { label: "Psychic", value: "psychic" },
  { label: "Dark", value: "dark" },
  { label: "Ground", value: "ground" },
  { label: "Poison", value: "poison" },
  { label: "Flying", value: "flying" },
];
